### ISSUE TITLE
Reduce Radius Minimum

### ISSUE THREAD

**Issue by DarekLin** [wojlin/gpx-heatmap#1]
Congratulations on a great application. Now I can view all traces of my activity on the map.
However, I would have a small request to reduce the Radius minimum value so that the lines drawn are thinner.
In addition, it would be nice if the app remembered the settings.

**Comment by wojlin** [comment]
Thanks for the kind words
I fixed all that stuff in the last commit:  [0936bf4](https://github.com/wojlin/gpx-heatmap/commit/0936bf4c32248d2d366f6e6405a5fe6051da6aa9)
issue can be closed
